"""parent_id deleted in usertable

Revision ID: 88f92332ed7a
Revises: fdddabad7e43
Create Date: 2024-07-04 03:25:02.289711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f92332ed7a'
down_revision = 'fdddabad7e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        # batch_op.create_foreign_key('user_ibfk_1', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###
